apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ynnaegla
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ynnaegla:4caca8c9e4b8c3b9ac71cd14ef51938791d4eda2@sha256:7b009aa8484dd11054812c9573ee9a1f5bbc216078ff45499b993b54b073b416
        name: container-image  
